/*=========================================================================

  Program:   OpenIGTLink Library
  Module:    $HeadURL: http://svn.na-mic.org/NAMICSandBox/trunk/OpenIGTLink2_beta/Source/igtlSensorMessage.h $
  Language:  C++
  Date:      $Date: 2009-12-16 23:58:02 -0500 (Wed, 16 Dec 2009) $
  Version:   $Revision: 5466 $

  Copyright (c) Insight Software Consortium. All rights reserved.

  This software is distributed WITHOUT ANY WARRANTY; without even
  the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
  PURPOSE.  See the above copyright notices for more information.

=========================================================================*/

#ifndef __igtlSensorMessage_h
#define __igtlSensorMessage_h

#include <string>

#include "igtlObject.h"
#include "igtlMath.h"
#include "igtlMessageBase.h"
#include "igtlTypes.h"

#include "igtlUnit.h"

namespace igtl
{

class IGTLCommon_EXPORT GetSensorMessage: public MessageBase
{

public:

  typedef GetSensorMessage				 Self;
  typedef MessageBase                    Superclass;
  typedef SmartPointer<Self>             Pointer;
  typedef SmartPointer<const Self>       ConstPointer;

  igtlTypeMacro(igtl::GetSensorMessage, igtl::MessageBase);
  igtlNewMacro(igtl::GetSensorMessage);


protected:
  GetSensorMessage();
  ~GetSensorMessage();
  
protected:
  virtual int  GetBodyPackSize() { return 0; };
  virtual int  PackBody()        { AllocatePack(); return 1; };
  virtual int  UnpackBody()      { return 1; };
};

class IGTLCommon_EXPORT StartSensorMessage: public GetSensorMessage
{
public:
  typedef StartSensorMessage             Self;
  typedef GetSensorMessage               Superclass;
  typedef SmartPointer<Self>	         Pointer;
  typedef SmartPointer<const Self>		 ConstPointer;

  igtlTypeMacro(igtl::StartSensorMessage, igtl::GetSensorMessage);
  igtlNewMacro(igtl::StartSensorMessage);

public:

  // Set/get time resolution. The time resolution is specified
  // as a 64-bit fixed-point used in OpenIGTLink time stamp.
  void        SetResolution(igtlUint64 res);
  igtlUint64  GetResolution();

protected:
  StartSensorMessage();
  ~StartSensorMessage();
  
protected:

  virtual int  GetBodyPackSize();
  virtual int  PackBody();
  virtual int  UnpackBody();

  igtlUint64   m_Resolution;

};

class IGTLCommon_EXPORT StopSensorMessage: public MessageBase
{
public:
  typedef StopSensorMessage                   Self;
  typedef MessageBase						  Superclass;
  typedef SmartPointer<Self>				  Pointer;
  typedef SmartPointer<const Self>			  ConstPointer;

  igtlTypeMacro(igtl::StopSensorMessage, igtl::MessageBase);
  igtlNewMacro(igtl::StopSensorMessage);

protected:
  StopSensorMessage();
  ~StopSensorMessage();

protected:
  virtual int  GetBodyPackSize() { return 0; };
  virtual int  PackBody()        { AllocatePack(); return 1; };
  virtual int  UnpackBody()      { return 1; };

};


class IGTLCommon_EXPORT RTSSensorMessage: public MessageBase
{
public:
  typedef RTSSensorMessage			     Self;
  typedef MessageBase                    Superclass;
  typedef SmartPointer<Self>             Pointer;
  typedef SmartPointer<const Self>       ConstPointer;

  // Status type
  enum {
    STATUS_SUCCESS = 0,
    STATUS_ERROR = 1
  };


  igtlTypeMacro(igtl::RTSSensorMessage, igtl::MessageBase);
  igtlNewMacro(igtl::RTSSensorMessage);

  void          SetStatus(igtlUint8 status){ this->m_Status = status; }
  igtlUint8     GetStatus()                { return this->m_Status; };

protected:
  RTSSensorMessage();
  ~RTSSensorMessage();

  igtlUint8 m_Status;

protected:
  virtual int  GetBodyPackSize();
  virtual int  PackBody();
  virtual int  UnpackBody();

};

class IGTLCommon_EXPORT SensorMessage: public MessageBase
{
public:
  typedef SensorMessage                  Self;
  typedef MessageBase                    Superclass;
  typedef SmartPointer<Self>             Pointer;
  typedef SmartPointer<const Self>       ConstPointer;

  igtlTypeMacro(igtl::SensorMessage, igtl::MessageBase);
  igtlNewMacro(igtl::SensorMessage);

public:

  int          SetLength(unsigned int n);
  unsigned int GetLength();

  //int        SetStatus(int i);
  int          SetUnit(igtlUnit unit);
  int          SetUnit(igtl::Unit * unit);
  igtlUnit     GetUnit();
  int          GetUnit(igtl::Unit * unit);

  int          SetValue(igtlFloat64 * data);       // Set sensor values from array of 64-bit floating data
  int          SetValue(unsigned int i, igtlFloat64 value); // Set i-th sensor value
  igtlFloat64  GetValue(unsigned int i);      // Get i-th sensor value

protected:
  SensorMessage();
  ~SensorMessage();
  
protected:

  virtual int  GetBodyPackSize();
  virtual int  PackBody();
  virtual int  UnpackBody();
  
  igtlUint8    m_Length;  // Length of sensor array
  igtlUint8    m_Status;  // Sensor status (Reserved)
  igtlUnit     m_Unit;    // Unit (generated by igtl::Unit::Pack())
  
  std::vector<igtlFloat64> m_Array;

};


} // namespace igtl

#endif // _igtlSensorMessage_h


